table_plane_extractor/Plane[] table_plane_equations
vision_msgs/BoundingBox3DArray table_bbs
geometry_msgs/Transform placement_surface_to_wrist # Placement surface for the object in EEF frame (hand_palm_link for sasha)
---
---